[package]
name = "task"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
mongodb = "2.0"
futures = "0.3"
serde_json = "1.0"
serde = { version = "1.0.202", features = ["derive"] }
reqwest = "0.12.4"
rand = "0.8.5"
actix-files = "0.6"
actix-cors = "0.7.0"


